import type {
  IRDecl,
  IREnum,
  IRProperty,
  IRStruct,
  IRTypeAlias,
  IRUnion,
  SwiftTypeRef,
} from "./ir";

/**
 * Renders IR declarations as Swift source.
 *
 * Conventions:
 * - Structs are `Codable, Equatable, Sendable` with mutable `var` stored
 *   properties and an explicit memberwise init (so optional and defaulted
 *   fields get call-site defaults).
 * - Literal-pinned fields (`z.literal`) become `let` constants with initial
 *   values: Swift's synthesized Codable encodes them but skips them during
 *   decoding, which is exactly the wire behavior we want.
 * - Non-frozen enums implement RawRepresentable manually and route unknown
 *   raw values into `.unknown(String)`; Codable comes from the standard
 *   library's RawRepresentable default implementations.
 * - Discriminated unions decode the discriminator first, then re-decode the
 *   full payload from the same decoder.
 */

const HEADER = `// Generated by packages/shared/codegen — DO NOT EDIT.
// Regenerate with \`pnpm --filter @repo/shared codegen\`.

import Foundation
`;

const SWIFT_KEYWORDS = new Set([
  "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
  "init", "inout", "internal", "let", "open", "operator", "private", "precedencegroup",
  "protocol", "public", "rethrows", "static", "struct", "subscript", "typealias", "var",
  "break", "case", "catch", "continue", "default", "defer", "do", "else", "fallthrough",
  "for", "guard", "if", "in", "repeat", "return", "throw", "switch", "where", "while",
  "as", "any", "false", "is", "nil", "self", "super", "throws", "true", "try", "Self", "Type",
]);

export function emitSwiftFile(decls: IRDecl[]): string {
  const rendered = decls.map((decl) => renderDecl(decl, 0));
  return `${HEADER}\n${rendered.join("\n\n")}\n`;
}

function renderDecl(decl: IRDecl, depth: number): string {
  switch (decl.kind) {
    case "struct":
      return renderStruct(decl, depth);
    case "enum":
      return renderEnum(decl, depth);
    case "union":
      return renderUnion(decl, depth);
    case "alias":
      return renderAlias(decl, depth);
  }
}

// ---------------------------------------------------------------------------
// Structs
// ---------------------------------------------------------------------------

function renderStruct(decl: IRStruct, depth: number): string {
  const lines: string[] = [];
  lines.push(...docLines(decl.doc));
  lines.push(`public struct ${decl.name}: Codable, Equatable, Sendable {`);

  for (const nested of decl.nested) {
    lines.push(...indented(renderDecl(nested, 0)), "");
  }

  for (const property of decl.properties) {
    lines.push(...indented(renderProperty(property)));
  }

  if (decl.properties.length > 0) {
    lines.push("");
  }
  lines.push(...indented(renderInit(decl)));

  const codingKeys = renderCodingKeys(decl.properties);
  if (codingKeys) {
    lines.push("", ...indented(codingKeys));
  }

  lines.push("}");
  return indentBlock(lines, depth);
}

function renderProperty(property: IRProperty): string[] {
  const lines = docLines(property.doc);
  const name = escapeIdentifier(property.swiftName);
  if (property.constValue !== undefined) {
    lines.push(`public let ${name} = ${swiftLiteral(property.constValue)}`);
  } else {
    lines.push(`public var ${name}: ${renderType(property.type)}`);
  }
  return lines;
}

function renderInit(decl: IRStruct): string[] {
  const settable = decl.properties.filter((property) => property.constValue === undefined);
  if (settable.length === 0) {
    return ["public init() {}"];
  }

  const params = settable.map((property, index) => {
    const name = escapeIdentifier(property.swiftName);
    const suffix = property.initDefault === undefined ? "" : ` = ${property.initDefault}`;
    const comma = index === settable.length - 1 ? "" : ",";
    return `    ${name}: ${renderType(property.type)}${suffix}${comma}`;
  });
  const assignments = settable.map((property) => {
    const name = escapeIdentifier(property.swiftName);
    return `    self.${name} = ${name}`;
  });
  return ["public init(", ...params, ") {", ...assignments, "}"];
}

function renderCodingKeys(properties: IRProperty[]): string[] | undefined {
  const hasRename = properties.some((property) => property.swiftName !== property.jsonKey);
  // Explicit CodingKeys for literal-pinned `let` properties keeps them encoded
  // while silencing the "immutable property will not be decoded" warning.
  const hasConst = properties.some((property) => property.constValue !== undefined);
  if (!hasRename && !hasConst) {
    return undefined;
  }
  const lines = ["private enum CodingKeys: String, CodingKey {"];
  for (const property of properties) {
    const name = escapeIdentifier(property.swiftName);
    lines.push(
      property.swiftName === property.jsonKey
        ? `    case ${name}`
        : `    case ${name} = "${property.jsonKey}"`,
    );
  }
  lines.push("}");
  return lines;
}

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

function renderEnum(decl: IREnum, depth: number): string {
  return decl.nonFrozen ? renderNonFrozenEnum(decl, depth) : renderFrozenEnum(decl, depth);
}

function renderFrozenEnum(decl: IREnum, depth: number): string {
  const lines: string[] = [];
  lines.push(...docLines(decl.doc));
  lines.push(`public enum ${decl.name}: String, Codable, CaseIterable, Sendable {`);
  for (const enumCase of decl.cases) {
    lines.push(...indented(renderEnumCase(enumCase.name, enumCase.rawValue)));
  }
  lines.push("}");
  return indentBlock(lines, depth);
}

function renderNonFrozenEnum(decl: IREnum, depth: number): string {
  const lines: string[] = [];
  lines.push(...docLines(decl.doc));
  lines.push(`public enum ${decl.name}: RawRepresentable, Codable, Equatable, Sendable {`);
  for (const enumCase of decl.cases) {
    lines.push(`    case ${escapeIdentifier(enumCase.name)}`);
  }
  lines.push("    /// A value this client version doesn't recognize yet.");
  lines.push("    case unknown(String)");
  lines.push("");
  lines.push("    public init(rawValue: String) {");
  lines.push("        switch rawValue {");
  for (const enumCase of decl.cases) {
    lines.push(
      `        case ${swiftLiteral(enumCase.rawValue)}: self = .${escapeIdentifier(enumCase.name)}`,
    );
  }
  lines.push("        default: self = .unknown(rawValue)");
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    public var rawValue: String {");
  lines.push("        switch self {");
  for (const enumCase of decl.cases) {
    lines.push(
      `        case .${escapeIdentifier(enumCase.name)}: ${swiftLiteral(enumCase.rawValue)}`,
    );
  }
  lines.push("        case .unknown(let value): value");
  lines.push("        }");
  lines.push("    }");
  lines.push("}");
  return indentBlock(lines, depth);
}

function renderEnumCase(name: string, rawValue: string): string[] {
  const escaped = escapeIdentifier(name);
  return name === rawValue
    ? [`case ${escaped}`]
    : [`case ${escaped} = ${swiftLiteral(rawValue)}`];
}

// ---------------------------------------------------------------------------
// Discriminated unions
// ---------------------------------------------------------------------------

function renderUnion(decl: IRUnion, depth: number): string {
  const lines: string[] = [];
  lines.push(...docLines(decl.doc));
  lines.push(`public enum ${decl.name}: Codable, Equatable, Sendable {`);

  for (const nested of decl.nested) {
    lines.push(...indented(renderDecl(nested, 0)), "");
  }

  for (const variant of decl.variants) {
    lines.push(`    case ${escapeIdentifier(variant.caseName)}(${variant.typeName})`);
  }
  if (decl.nonFrozen) {
    lines.push("    /// A variant this client version doesn't recognize yet.");
    lines.push("    case unknown(type: String)");
  }

  lines.push("");
  lines.push("    private enum DiscriminatorKeys: String, CodingKey {");
  lines.push(`        case discriminator = "${decl.discriminatorKey}"`);
  lines.push("    }");
  lines.push("");
  lines.push("    public init(from decoder: any Decoder) throws {");
  lines.push("        let container = try decoder.container(keyedBy: DiscriminatorKeys.self)");
  lines.push("        switch try container.decode(String.self, forKey: .discriminator) {");
  for (const variant of decl.variants) {
    lines.push(`        case ${swiftLiteral(variant.discriminatorValue)}:`);
    lines.push(
      `            self = .${escapeIdentifier(variant.caseName)}(try ${variant.typeName}(from: decoder))`,
    );
  }
  lines.push("        case let unrecognized:");
  if (decl.nonFrozen) {
    lines.push("            self = .unknown(type: unrecognized)");
  } else {
    lines.push("            throw DecodingError.dataCorruptedError(");
    lines.push("                forKey: .discriminator,");
    lines.push("                in: container,");
    lines.push(
      `                debugDescription: "Unknown ${decl.name} discriminator: \\(unrecognized)"`,
    );
    lines.push("            )");
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("");
  lines.push("    public func encode(to encoder: any Encoder) throws {");
  lines.push("        switch self {");
  for (const variant of decl.variants) {
    lines.push(`        case .${escapeIdentifier(variant.caseName)}(let payload):`);
    lines.push("            try payload.encode(to: encoder)");
  }
  if (decl.nonFrozen) {
    lines.push("        case .unknown(let type):");
    lines.push("            var container = encoder.container(keyedBy: DiscriminatorKeys.self)");
    lines.push("            try container.encode(type, forKey: .discriminator)");
  }
  lines.push("        }");
  lines.push("    }");
  lines.push("}");
  return indentBlock(lines, depth);
}

// ---------------------------------------------------------------------------
// Aliases, types, helpers
// ---------------------------------------------------------------------------

function renderAlias(decl: IRTypeAlias, depth: number): string {
  const lines = docLines(decl.doc);
  lines.push(`public typealias ${decl.name} = ${renderType(decl.target)}`);
  return indentBlock(lines, depth);
}

export function renderType(type: SwiftTypeRef): string {
  switch (type.kind) {
    case "string":
      return "String";
    case "int":
      return "Int";
    case "double":
      return "Double";
    case "bool":
      return "Bool";
    case "uuid":
      return "UUID";
    case "datetime":
      return "ISODateTimeString";
    case "json":
      return "JSONValue";
    case "array":
      return `[${renderType(type.element)}]`;
    case "dictionary":
      return `[String: ${renderType(type.value)}]`;
    case "named":
      return type.name;
    case "optional":
      return `${renderType(type.wrapped)}?`;
  }
}

function swiftLiteral(value: string | number | boolean): string {
  return typeof value === "string" ? JSON.stringify(value) : String(value);
}

function escapeIdentifier(name: string): string {
  return SWIFT_KEYWORDS.has(name) ? `\`${name}\`` : name;
}

function docLines(doc?: string): string[] {
  if (!doc) {
    return [];
  }
  return doc
    .split("\n")
    .map((line) => `/// ${line}`.trimEnd());
}

function indented(lines: string[] | string): string[] {
  const array = typeof lines === "string" ? lines.split("\n") : lines;
  return array.map((line) => (line.length === 0 ? line : `    ${line}`));
}

function indentBlock(lines: string[], depth: number): string {
  const prefix = "    ".repeat(depth);
  return lines.map((line) => (line.length === 0 ? line : `${prefix}${line}`)).join("\n");
}
