import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { emitSwiftFile } from "./emit-swift";
import { FIXTURES } from "./fixtures";
import type { GeneratedFile } from "./ir";
import { introspect, pascalCase, swiftCaseName } from "./introspect";
import { MANIFEST } from "./manifest";

/**
 * Zod → Swift codegen entry point.
 *
 *   pnpm --filter @repo/shared codegen          # write generated output
 *   pnpm --filter @repo/shared codegen:check    # fail if output is stale (CI)
 *
 * Output root: apps/ios/Modules/CoreAPI (checked in; the iOS app builds
 * against the committed Swift, never against a live generator).
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_ROOT = path.resolve(here, "../../../apps/ios/Modules/CoreAPI");
const GENERATED_DIR = "Sources/CoreAPI/Generated";
const FIXTURES_DIR = "Tests/CoreAPITests/Fixtures";
const TESTS_FILE = "Tests/CoreAPITests/FixtureDecodingTests.generated.swift";

function buildOutputs(): GeneratedFile[] {
  const outputs: GeneratedFile[] = [];

  const decls = introspect(MANIFEST);
  const groups: string[] = [];
  for (const entry of MANIFEST) {
    if (!groups.includes(entry.group)) {
      groups.push(entry.group);
    }
  }
  for (const group of groups) {
    const groupDecls = MANIFEST.filter((entry) => entry.group === group).map((entry) => {
      const decl = decls.get(entry.swiftName);
      if (!decl) {
        throw new Error(`Missing IR for ${entry.swiftName}`);
      }
      return decl;
    });
    outputs.push({
      path: `${GENERATED_DIR}/${group}.generated.swift`,
      content: emitSwiftFile(groupDecls),
    });
  }

  outputs.push(...buildFixtureOutputs());
  return outputs;
}

function buildFixtureOutputs(): GeneratedFile[] {
  const outputs: GeneratedFile[] = [];
  const manifestNames = new Set(MANIFEST.map((entry) => entry.swiftName));
  const fixtureNames = new Set<string>();
  const testFunctions: string[] = [];

  for (const fixture of FIXTURES) {
    const name = `${fixture.typeName}.${fixture.caseName}`;
    if (fixtureNames.has(name)) {
      throw new Error(`Duplicate fixture: ${name}`);
    }
    fixtureNames.add(name);
    if (!manifestNames.has(fixture.typeName)) {
      throw new Error(`Fixture ${name} references unknown manifest type ${fixture.typeName}`);
    }

    let parsed: unknown;
    try {
      parsed = fixture.schema.parse(fixture.value);
    } catch (error) {
      throw new Error(`Fixture ${name} fails schema validation: ${String(error)}`, {
        cause: error,
      });
    }
    outputs.push({
      path: `${FIXTURES_DIR}/${name}.json`,
      content: `${JSON.stringify(parsed, null, 2)}\n`,
    });

    const functionName = `${swiftCaseName(fixture.typeName)}${pascalCase(fixture.caseName)}`;
    testFunctions.push(
      [
        `    @Test func ${functionName}() throws {`,
        `        try assertRoundTrip(${fixture.typeName}.self, fixture: "${name}")`,
        "    }",
      ].join("\n"),
    );
  }

  const testFile = `// Generated by packages/shared/codegen — DO NOT EDIT.
// Regenerate with \`pnpm --filter @repo/shared codegen\`.

import CoreAPI
import Foundation
import Testing

/// Round-trips every TypeScript-produced wire fixture through the generated
/// Swift Codable types: decode → encode → decode → compare. Fixture JSON is
/// validated against the Zod schemas at generation time, so a green run means
/// both languages agree on the wire format.
@Suite("CoreAPI wire fixtures")
struct FixtureDecodingTests {
${testFunctions.join("\n\n")}
}

private func assertRoundTrip<T: Codable & Equatable>(
    _ type: T.Type,
    fixture: String
) throws {
    let url = try #require(Bundle.module.url(
        forResource: fixture,
        withExtension: "json",
        subdirectory: "Fixtures"
    ))
    let data = try Data(contentsOf: url)
    let decoder = JSONDecoder()
    let decoded = try decoder.decode(T.self, from: data)
    let reencoded = try JSONEncoder().encode(decoded)
    let redecoded = try decoder.decode(T.self, from: reencoded)
    #expect(decoded == redecoded)
}
`;
  outputs.push({ path: TESTS_FILE, content: testFile });
  return outputs;
}

/** Files the generator owns: anything matching these on disk but not in the output set is an orphan. */
function findOrphans(outputs: GeneratedFile[]): string[] {
  const owned = new Set(outputs.map((file) => file.path));
  const orphans: string[] = [];
  const scan = (relativeDir: string, matches: (name: string) => boolean) => {
    const absolute = path.join(OUTPUT_ROOT, relativeDir);
    if (!existsSync(absolute)) {
      return;
    }
    for (const name of readdirSync(absolute)) {
      const relative = `${relativeDir}/${name}`;
      if (matches(name) && !owned.has(relative)) {
        orphans.push(relative);
      }
    }
  };
  scan(GENERATED_DIR, (name) => name.endsWith(".generated.swift"));
  scan(FIXTURES_DIR, (name) => name.endsWith(".json"));
  return orphans;
}

function main(): void {
  const checkMode = process.argv.includes("--check");
  const outputs = buildOutputs();
  const orphans = findOrphans(outputs);

  const stale: string[] = [];
  const written: string[] = [];
  for (const file of outputs) {
    const absolute = path.join(OUTPUT_ROOT, file.path);
    const current = existsSync(absolute) ? readFileSync(absolute, "utf8") : undefined;
    if (current === file.content) {
      continue;
    }
    if (checkMode) {
      stale.push(file.path);
    } else {
      mkdirSync(path.dirname(absolute), { recursive: true });
      writeFileSync(absolute, file.content);
      written.push(file.path);
    }
  }

  if (checkMode) {
    if (stale.length > 0 || orphans.length > 0) {
      for (const file of stale) {
        console.error(`stale: ${file}`);
      }
      for (const file of orphans) {
        console.error(`orphaned: ${file}`);
      }
      console.error(
        "\nGenerated Swift is out of date. Run `pnpm --filter @repo/shared codegen` and commit the result.",
      );
      process.exit(1);
    }
    console.log(`codegen check passed (${outputs.length} files up to date)`);
    return;
  }

  for (const orphan of orphans) {
    rmSync(path.join(OUTPUT_ROOT, orphan));
  }
  console.log(
    `codegen: ${outputs.length} files (${written.length} written, ${orphans.length} orphans removed)`,
  );
}

main();
