// Generated by packages/shared/codegen — DO NOT EDIT.
// Regenerate with `pnpm --filter @repo/shared codegen`.

import CoreAPI
import Foundation
import Testing

/// Round-trips every TypeScript-produced wire fixture through the generated
/// Swift Codable types: decode → encode → decode → compare. Fixture JSON is
/// validated against the Zod schemas at generation time, so a green run means
/// both languages agree on the wire format.
@Suite("CoreAPI wire fixtures")
struct FixtureDecodingTests {
    @Test func sessionSummaryFull() throws {
        try assertRoundTrip(SessionSummary.self, fixture: "SessionSummary.full")
    }

    @Test func sessionSummaryMinimal() throws {
        try assertRoundTrip(SessionSummary.self, fixture: "SessionSummary.minimal")
    }

    @Test func messageAssistant() throws {
        try assertRoundTrip(Message.self, fixture: "Message.assistant")
    }

    @Test func pullRequestClientStateCreating() throws {
        try assertRoundTrip(PullRequestClientState.self, fixture: "PullRequestClientState.creating")
    }

    @Test func pullRequestClientStateFailed() throws {
        try assertRoundTrip(PullRequestClientState.self, fixture: "PullRequestClientState.failed")
    }

    @Test func pullRequestClientStateCreated() throws {
        try assertRoundTrip(PullRequestClientState.self, fixture: "PullRequestClientState.created")
    }

    @Test func agentSettingsInputPartial() throws {
        try assertRoundTrip(AgentSettingsInput.self, fixture: "AgentSettingsInput.partial")
    }

    @Test func sessionInfoResponseFull() throws {
        try assertRoundTrip(SessionInfoResponse.self, fixture: "SessionInfoResponse.full")
    }

    @Test func createSessionRequestFull() throws {
        try assertRoundTrip(CreateSessionRequest.self, fixture: "CreateSessionRequest.full")
    }

    @Test func createSessionResponseCreated() throws {
        try assertRoundTrip(CreateSessionResponse.self, fixture: "CreateSessionResponse.created")
    }

    @Test func listSessionsResponsePaginated() throws {
        try assertRoundTrip(ListSessionsResponse.self, fixture: "ListSessionsResponse.paginated")
    }

    @Test func deleteSessionResponseDeleted() throws {
        try assertRoundTrip(DeleteSessionResponse.self, fixture: "DeleteSessionResponse.deleted")
    }

    @Test func clientMessageChatMessage() throws {
        try assertRoundTrip(ClientMessage.self, fixture: "ClientMessage.chatMessage")
    }

    @Test func clientMessageSyncRequest() throws {
        try assertRoundTrip(ClientMessage.self, fixture: "ClientMessage.syncRequest")
    }

    @Test func clientMessageSessionMarkRead() throws {
        try assertRoundTrip(ClientMessage.self, fixture: "ClientMessage.sessionMarkRead")
    }

    @Test func clientMessageOperationCancel() throws {
        try assertRoundTrip(ClientMessage.self, fixture: "ClientMessage.operationCancel")
    }

    @Test func serverMessageConnected() throws {
        try assertRoundTrip(ServerMessage.self, fixture: "ServerMessage.connected")
    }

    @Test func serverMessageSyncResponse() throws {
        try assertRoundTrip(ServerMessage.self, fixture: "ServerMessage.syncResponse")
    }

    @Test func serverMessageOperationError() throws {
        try assertRoundTrip(ServerMessage.self, fixture: "ServerMessage.operationError")
    }

    @Test func serverMessageAgentChunks() throws {
        try assertRoundTrip(ServerMessage.self, fixture: "ServerMessage.agentChunks")
    }

    @Test func serverMessageAgentFinish() throws {
        try assertRoundTrip(ServerMessage.self, fixture: "ServerMessage.agentFinish")
    }

    @Test func serverMessageAgentReady() throws {
        try assertRoundTrip(ServerMessage.self, fixture: "ServerMessage.agentReady")
    }

    @Test func serverMessageUserMessage() throws {
        try assertRoundTrip(ServerMessage.self, fixture: "ServerMessage.userMessage")
    }

    @Test func serverMessageEditorReady() throws {
        try assertRoundTrip(ServerMessage.self, fixture: "ServerMessage.editorReady")
    }

    @Test func uIMessageWithParts() throws {
        try assertRoundTrip(UIMessage.self, fixture: "UIMessage.withParts")
    }

    @Test func userSessionsServerMessageConnected() throws {
        try assertRoundTrip(UserSessionsServerMessage.self, fixture: "UserSessionsServerMessage.connected")
    }

    @Test func userSessionsServerMessageSummaryCreated() throws {
        try assertRoundTrip(UserSessionsServerMessage.self, fixture: "UserSessionsServerMessage.summaryCreated")
    }

    @Test func userSessionsServerMessageSummaryUpdated() throws {
        try assertRoundTrip(UserSessionsServerMessage.self, fixture: "UserSessionsServerMessage.summaryUpdated")
    }

    @Test func userSessionsServerMessageSummaryRemoved() throws {
        try assertRoundTrip(UserSessionsServerMessage.self, fixture: "UserSessionsServerMessage.summaryRemoved")
    }

    @Test func userSessionsServerMessageResyncRequired() throws {
        try assertRoundTrip(UserSessionsServerMessage.self, fixture: "UserSessionsServerMessage.resyncRequired")
    }

    @Test func tokenResponseFull() throws {
        try assertRoundTrip(TokenResponse.self, fixture: "TokenResponse.full")
    }

    @Test func openAIDeviceStartResponseStarted() throws {
        try assertRoundTrip(OpenAIDeviceStartResponse.self, fixture: "OpenAIDeviceStartResponse.started")
    }

    @Test func openAIDeviceAttemptResponsePending() throws {
        try assertRoundTrip(OpenAIDeviceAttemptResponse.self, fixture: "OpenAIDeviceAttemptResponse.pending")
    }

    @Test func claudeStatusResponseConnected() throws {
        try assertRoundTrip(ClaudeStatusResponse.self, fixture: "ClaudeStatusResponse.connected")
    }

    @Test func repoPrivate() throws {
        try assertRoundTrip(Repo.self, fixture: "Repo.private")
    }

    @Test func branchDefault() throws {
        try assertRoundTrip(Branch.self, fixture: "Branch.default")
    }

    @Test func modelsResponseCatalog() throws {
        try assertRoundTrip(ModelsResponse.self, fixture: "ModelsResponse.catalog")
    }

    @Test func attachmentDescriptorImage() throws {
        try assertRoundTrip(AttachmentDescriptor.self, fixture: "AttachmentDescriptor.image")
    }

    @Test func uploadAttachmentResponseSingle() throws {
        try assertRoundTrip(UploadAttachmentResponse.self, fixture: "UploadAttachmentResponse.single")
    }

    @Test func agentSettingsClaudeDefaults() throws {
        try assertRoundTrip(AgentSettings.self, fixture: "AgentSettings.claudeDefaults")
    }

    @Test func agentSettingsCodex() throws {
        try assertRoundTrip(AgentSettings.self, fixture: "AgentSettings.codex")
    }

    @Test func networkAccessConfigOpen() throws {
        try assertRoundTrip(NetworkAccessConfig.self, fixture: "NetworkAccessConfig.open")
    }

    @Test func networkAccessConfigLocked() throws {
        try assertRoundTrip(NetworkAccessConfig.self, fixture: "NetworkAccessConfig.locked")
    }

    @Test func networkAccessConfigDefault() throws {
        try assertRoundTrip(NetworkAccessConfig.self, fixture: "NetworkAccessConfig.default")
    }

    @Test func networkAccessConfigCustom() throws {
        try assertRoundTrip(NetworkAccessConfig.self, fixture: "NetworkAccessConfig.custom")
    }

    @Test func repoEnvironmentFull() throws {
        try assertRoundTrip(RepoEnvironment.self, fixture: "RepoEnvironment.full")
    }

    @Test func createRepoEnvironmentRequestDefaults() throws {
        try assertRoundTrip(CreateRepoEnvironmentRequest.self, fixture: "CreateRepoEnvironmentRequest.defaults")
    }

    @Test func voiceTranscriptionTokenResponseIssued() throws {
        try assertRoundTrip(VoiceTranscriptionTokenResponse.self, fixture: "VoiceTranscriptionTokenResponse.issued")
    }

    @Test func integrationLinksResponseLinked() throws {
        try assertRoundTrip(IntegrationLinksResponse.self, fixture: "IntegrationLinksResponse.linked")
    }
}

private func assertRoundTrip<T: Codable & Equatable>(
    _ type: T.Type,
    fixture: String
) throws {
    let url = try #require(Bundle.module.url(
        forResource: fixture,
        withExtension: "json",
        subdirectory: "Fixtures"
    ))
    let data = try Data(contentsOf: url)
    let decoder = JSONDecoder()
    let decoded = try decoder.decode(T.self, from: data)
    let reencoded = try JSONEncoder().encode(decoded)
    let redecoded = try decoder.decode(T.self, from: reencoded)
    #expect(decoded == redecoded)
}
